name: funtictac
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  delayed_display: ^2.0.0
  anitex: ^3.0.1
  assets_audio_player: ^3.1.1
  rflutter_alert: ^2.0.7
  lottie: ^3.1.2
  tapsell_plus: ^2.2.7
  blurbox: 0.0.4
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.3.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/app_icon_android.png"
  image_path_ios: "assets/images/app_icon_ios.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/
    - assets/lottie/
  fonts:
    - family: Paytone
      fonts:
        - asset: assets/fonts/PaytoneOne-Regular.ttf
    - family: Carter
      fonts:
        - asset: assets/fonts/CarterOne-Regular.ttf

    - family: morvarid
      fonts:
        - asset: assets/fonts/morvarid.ttf
