// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7tpj85xt7hVtf00IwH-7RqwSVsjft5I0',
    appId: '1:121198200117:web:ddd35d861295ecbe2cb87c',
    messagingSenderId: '121198200117',
    projectId: 'noghtebaz',
    authDomain: 'noghtebaz.firebaseapp.com',
    storageBucket: 'noghtebaz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH3bK8lEVBPNGaoGeKNtRJ_O73M1V0l0E',
    appId: '1:121198200117:android:5ab378f2601e88d82cb87c',
    messagingSenderId: '121198200117',
    projectId: 'noghtebaz',
    storageBucket: 'noghtebaz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9fU6miAB38PV7a2IvT27QncGv8ha2HKU',
    appId: '1:121198200117:ios:820855688984b6432cb87c',
    messagingSenderId: '121198200117',
    projectId: 'noghtebaz',
    storageBucket: 'noghtebaz.appspot.com',
    iosBundleId: 'com.funtictac.funtictacgame',
  );
}
